apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dmz-tainter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dmz-tainter
subjects:
- kind: ServiceAccount
  name: dmz-tainter
  namespace: default